### ISSUE TITLE
Pypi update to current version of ibis-mssql

### ISSUE THREAD

**Issue by safrazRampersaud** [Quansight/ibis-mssql#13]
Pip install pulls down the previous version of the wheel. Should we update this? https://widdowquinn.github.io/coding/update-pypi-package/.  Happy to see this through just don't know if there are permission issues along the way.

**Comment by xmnlab** [comment]
@safrazRampersaud, I will cut a new release on Monday. thanks!

**Comment by xmnlab** [comment]
@safrazRampersaud new version released https://pypi.org/project/ibis-mssql/
thanks!
