### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by pritukam** [Quansight/ibis-mssql#3]
Hi Team,

The project that I am working on requires an mssql connector for the ibis framework. 

Before we start using the connector, we were wondering if there are any plans to change the licensing (now or in the future) of the code made available, so that we could evaluate the usage of the provided connector in our project. 

Your response on this is highly appreciated.

Thanks.

**Comment by xmnlab** [comment]
Hi @pritukam ! I hope my message here is not too late.

The license here is Apache 2.0, the same used by Ibis-framework.

I don't think it would be changed in the future, as it should keep the same license that ibis uses.

**Comment by xmnlab** [comment]
@pritukam , I think we can close this issue now, but  feel free to re-open it, if it is needed. thanks!
