### ISSUE TITLE
Project Revival

### ISSUE THREAD

**Issue by jwcook23** [Quansight/ibis-mssql#4]
@costrouc is this project still alive, if so are you looking for contributions? Sorry for the general question. Thanks!

**Comment by xmnlab** [comment]
Maybe I can help to answer this one. I think any contribution would be very appreciated. Currently, the development of this project is not so active, but I can help to review PRs.

**Comment by jwcook23** [comment]
@xmnlab Sounds good! Just wanted to make sure PR's would be reviewed. I'll make separate issues here as needed.

**Comment by xmnlab** [comment]
sounds great! thank you!
