### ISSUE TITLE
ibis-mssql import fix?

### ISSUE THREAD

**Issue by safrazRampersaud** [Quansight/ibis-mssql#5]
I am using ibis-mssql and it is fantastic for my purposes!  I noticed that I had to change some imports to coordinate it with the ibis-project.  Are you accepting PRs for this to make it easier for other users to get started? BTW: Will this repo be separately maintained or will it be integrated in the ibis-project in the near future?

**Comment by xmnlab** [comment]
> I am using ibis-mssql and it is fantastic for my purposes!

hi @safrazRampersaud, thanks for the feedback!

>  noticed that I had to change some imports to coordinate it with the ibis-project. Are you accepting PRs for this to make it easier for other users to get started? 

sure thing, any PR is very welcome! thank you!

>  BTW: Will this repo be separately maintained or will it be integrated in the ibis-project in the near future?

I think we will keep it separated from the ibis-framework core. Actually the ibis core devs are working to keep the ibis framework pluggable ... so each project can have a different workflow and development cycle. For example, OmniSci backend was already moved from ibis-framework core to its own repository (https://github.com/omnisci/ibis-omniscidb).
